data/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(template_name="data/index.html"), name='index'),
    #url(r'^data/sign_in/$', views.sign_in, name='sign_in'),
    #url(r'^data/sign_in/', views.UserView.as_view(),name="sign_in"),
    url(r'^data/sign_in/', views.sign_in, name='sign_in'),
    url(r'^data/login/', views.redirect,name="login"),
    #url(r'^data/create/$', views.UserView.as_view(), name='create'),
    url(r'^data/$', views.UserList.as_view(), name="user_view"),
    url(r'^data/(?P<pk>[0-9]+)/$', views.UserDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

proyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    #url(r'^$','data.views.actual_time', name='actual_time'),
    url(r'', include('data.urls')),
    url(r'^admin/', admin.site.urls),
    #url(r'^api-auth/', include('rest_framework.urls', namespace= 'rest_framework')),
]

data/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class User(models.Model):
    name = models.CharField(blank = False, max_length=150)
    email = models.EmailField(blank = False, unique=True)
    password = models.CharField(blank = False, max_length=50)
    birth_date = models.DateField()
    gender = models.CharField(blank = False, max_length=20)
    #list_subject = models.ForeignKey(Subject)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class Subject(models.Model):
    user = models.ForeignKey(User)
    # action = models.ForeignKey(Action)
    # transfer = models.ForeignKey(Transfer)
    # binnacle = models.ForeignKey(Binnacle)
    # checkpoint = models.ForeignKey(Checkpoint)

class Action(models.Model):
    description = models.TextField()
    type = models.SmallIntegerField()
    critical = models.CharField(max_length=1)
    num_day = models.IntegerField()
    day_week = models.SmallIntegerField()
    time = models.TimeField(default=timezone.now)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    #binnacle = models.ForeignKey(Binnacle)

    def __unicode__(self):
        return "%s - %s" % (self.type, self.description)

class SensorData(models.Model):
    accel_x = models.FloatField()
    accel_y = models.FloatField()
    accel_z = models.FloatField()
    compass = models.FloatField()
    #transfer = models.ForeignKey(Transfer)

    def __unicode__(self):
        return "(%s, %s, %s)" % (self.accel_x, self.accel_y, self.accel_z)

class Transfer(models.Model):
    sensor_data = models.OneToOneField(SensorData, primary_key=True)
    time = models.DateTimeField()
    x = models.FloatField()
    y = models.FloatField()
    z = models.FloatField()
    velocity = models.FloatField()
    course = models.FloatField()
    provider = models.TextField()
    time_gps = models.DateTimeField()
    gps = models.IntegerField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    #type_event = models.ForeignKey(TypeEvent)

    def __str__(self):
        return self.time

    def __unicode__(self):
        return "%s - %s" % (self.time, self.provider)

class Binnacle(models.Model):
    time = models.TimeField(default=timezone.now)
    accomplished = models.TextField()
    key = models.TextField()
    againstkey = models.TextField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, on_delete=models.CASCADE)
    def __unicode__(self):
        return "%s - %s" % (self.time, self.accomplished)

class Checkpoint(models.Model):
    x = models.FloatField()
    y = models.FloatField()
    z = models.FloatField()
    action = models.SmallIntegerField()
    time = models.TimeField()
    num_day = models.IntegerField()
    day_week = models.SmallIntegerField()
    day_month = models.SmallIntegerField()
    num_month = models.SmallIntegerField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    def __unicode__(self):
        return "%s - (%s, %s, %s)" % (self.time, self.x, self.y, self.z)

    def __unicode__(self):
        return self.user

data/forms.py
from django import forms
from .models import User

class NameFormField(forms.Form):
    name = forms.CharField(label='Nombre')

class UserForm(forms.ModelForm):

    name = forms.CharField(
                           widget = forms.TextInput(attrs={'id':'name', 'class':'active validate','placeholder':'Nombre Completo'})
    )
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'validate', 'placeholder': 'Email','type':'email'})
    )
    birth_date = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'datepicker', 'type': 'date'})
    )
    password = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'validate', 'placeholder': 'Password','type':'password'})
    )

    class Meta:
        model = User
        fields = '__all__'
        '''fields_classes = {
            'name' : NameFormField,
        }'''

data/views.py
from rest_framework.decorators import permission_classes
from rest_framework import generics
from rest_framework.permissions import AllowAny
from data.models import User
from data.serializers import UserSerializer
from django.shortcuts import render
from django import forms
from django.http import HttpResponse
from django.views import generic
from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import FormMixin, ProcessFormView
from django import forms
from .forms import UserForm

class IndexView(generic.TemplateView):

    def get_context_data(self, **kwargs):
        self.context = {'urls' : [('sign_in','Registrarse')]}
        return self.context
'''def index(request):
    context = {'urls': [('sign_in','Registrarse')]}
    return render(request, template, context)
'''

def redirect(request):
    form = UserForm()
    #template = "data/login.html"
    #return render(request, template, {'request':request.path})
    return render(request, 'data/login.html', {'form':form})

def sign_in(request):
    #template = "data/sign_in.html"
    #return render(request, template)
    form = UserForm()
    return render(request, 'data/login.html', {'form':form})

def create(request):
    return HttpResponse(request)

'''
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'email', 'password', 'birth_date', 'gender')
'''
'''class UserForm(forms.ModelForm):

    name = forms.CharField(label=_("Nombre"),
                           max_length=150,
                           widget = forms.TextInput,
    )

    class Meta:
        model = User
        fields = ('name',)
        exclude = ('id', 'email','password','birth_date', 'gender')
        widgets = {
            'name' : forms.Textarea(attrs={'cols':80, 'rows':20}),
        }
class UserView(generic.FormView):
    template_name = "data/login.html"
    form_class = UserForm
    #form_class =
    #success_url = "/data/login"

    def form_valid(self, form):
        return HttpResponse("valid")

    def form_invalid(self, form):
        return HttpResponse("invalid")
'''
@permission_classes((AllowAny,))
class UserList(generics.ListCreateAPIView):

    queryset = User.objects.all()
    serializer_class = UserSerializer

@permission_classes((AllowAny,))
class UserDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

data/templates/data/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <title>Deteccion de Anomalias en una Rutina</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <link rel="stylesheet" href="{%static 'materialize/css/materialize.min.css' %}" media="screen,projection"/>
        <link rel="stylesheet" href="{%static 'googleapis/material_icons.css' %}">
        <link rel="stylesheet" href="{%static 'css/style.css' %}" media="screen, projection">
        <script type="text/javascript" src="{%static 'jquery/jquery-2.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{%static 'materialize/js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{%static 'js/script.js' %}"></script>
    </head>
    <!--body class="container blue-grey lighten-5"-->
    <body class="container">
        <header class="blue-text text-darken-4">
            <h1 class="center">Deteccion de Anomalias en una Rutina</h1>
        </header>
        <nav class="blue darken-4" role="navigation">
            <div class="nav-wrapper">
                <a href="#!" class="brand-logo">Logo</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse" ><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    {% if urls %}
                        {%for url, name_url in urls %}
                            <li><a href="/data/{{ url }}/">{{ name_url }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    {% if urls %}
                        {%for url, name_url in urls %}
                            <li><a href="/data/{{ url }}/">{{ name_url }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="row">
            <div class="col s12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <footer>
            <p><strong>Andreina Cota Vidaurre</strong></p>
            <p>andre_k812@hotmail.com 2016 ®</p>
        </footer>
    </body>
</html>

data/templates/data/index.html
{% extends 'data/base.html' %}

{% block content %}
    <div class="card-panel hoverable">
		<h3>La deteccion de Anomalias es: ...</h3>
	</div>
{% endblock content %}

data/templates/data/login.html
{% extends 'data/base.html' %}

{% block content %}
    <h1>Registrarse</h1>
    <div class="row">
        <form method="POST" class="col s12">
            {% csrf_token %}
        <div class="row">
           <div class="input-field col s12">
              <i class="material-icons prefix">account_circle</i>
              <!--input placeholder="Nombre Completo" id="nombre" type="text" class="active validate" required-->
               {{form.name}}
              <label for="{{ form.name.name }}">Nombre</label>
           </div>
        </div>
            <div class="row">
               <div class="input-field col s12">
                   <i class="material-icons prefix">email</i>
                  <label for="id_email" data-error="No es valido">Email</label>
                   {{form.email}}
                  <!--input placeholder="Email" id="email" type="email" class="validate"-->
               </div>
            </div>
             <div class="row">
                 <div class="input-field col s12">
                <i class="material-icons prefix active">today</i>
                <label for="id_birth_date" class="active">Fecha de Nacimiento</label>
                {{form.birth_date}}
                <!--input id="birth_date" type="date" class="datepicker"-->
                 </div>
                 </div>
             <div class="row">
                 <div class="input-field col s6">
                     <i class="material-icons prefix">lock_outline</i>
                  <label for="id_password">Password</label>
                  {{form.password}}
                  <!--input id="password" type="password" placeholder="Password" class="validate" required-->
               </div>
                <div class="input-field col s6">
                  <label for="conf_password">Confirmar Password</label>
                  <input id="conf_password" type="password" placeholder="Password" class="validate" required>
               </div>
             </div>
            <div class="row">
                <div class="col s12">
                   <label class="active">Genero</label>
                   {{form.gender}}
                   <select class="browser-default" required>
                      <option value="" disabled selected>Selecciona tu genero</option>
                      <option value="1">Femenino</option>
                      <option value="2">Masculino</option>
                   </select>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input type="submit" class="btn waves-effect waves-light right" name="action" value="Registrar">
                </div>
            </div>
        </form>
      </div>
{% endblock %}

data/templates/data/sign_in.html
{% load staticfiles %}
{% load rest_framework %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign_in</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{%static 'materialize/css/materialize.min.css' %}" media="screen,projection"/>
    <link rel="stylesheet" href="{%static 'googleapis/material_icons.css' %}">
    <script type="text/javascript" src="{%static 'jquery/jquery-2.1.1.min.js' %}"></script>
	<script type="text/javascript" src="{%static 'materialize/js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{%static 'js/script.js' %}"></script>
</head>
<body class="container">
      <div class="row">
         <form class="col s12" action= "{% url 'create' %}" method="post">
             {% csrf_token %}
             <div class="row">
               <div class="input-field col s12">
                  <i class="material-icons prefix">account_circle</i>
                  <input placeholder="Nombre Completo" id="nombre" type="text" class="active validate" required>
                  <label for="nombre">Nombre</label>
               </div>
            </div>
            <div class="row">
               <div class="input-field col s12">
                   <i class="material-icons prefix">email</i>
                  <input placeholder="Email" id="email" type="email" class="validate">
                  <label for="email" data-error="No es valido">Email</label>
               </div>
            </div>
             <div class="row">
                 <div class="input-field col s12">
                <i class="material-icons prefix active">today</i>
                <label for="birth_date" class="active">Fecha de Nacimiento</label>
                <input id="birth_date" type="date" class="datepicker">
                 </div>
                 </div>
             <div class="row">
                 <div class="input-field col s6">
                     <i class="material-icons prefix">lock_outline</i>
                  <label for="password">Password</label>
                  <input id="password" type="password" placeholder="Password" class="validate" required>
               </div>
                <div class="input-field col s6">
                  <label for="conf_password">Confirmar Password</label>
                  <input id="conf_password" type="password" placeholder="Password" class="validate" required>
               </div>
             </div>
            <div class="row">
                <div class="col s12">
                   <label class="active">Genero</label>
                   <select class="browser-default" required>
                      <option value="" disabled selected>Selecciona tu genero</option>
                      <option value="1">Femenino</option>
                      <option value="2">Masculino</option>
                   </select>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input type="submit" class="btn waves-effect waves-light right" name="action" value="Registrar">
                </div>
            </div>
         </form>
      </div>
   </body>
</html>

data/templates/form.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8" />

	<meta name="viewport" 
		  content="width=device-width, initial-scale=1, maximum-scale=1" />

	<title>Puls3: Comunidad online de gente pro y (no sé que más escribir)</title>
	<link rel="stylesheet" href="normalize.css" />
	<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css' />
	<link rel="stylesheet" href="/static/estilos.css" />
	<link rel="stylesheet" href="/static/responsive.css" />
</head>
<body>
	<!-- comentario de lo que sea -->
	<header>
		<figure id="logo">
			<img src="logo.png" />
		</figure>
		<h1 id="titulo_header">Puls3: Comunidad de gente cool, atractiva y millonaria</h1>
		<figure id="avatar">
			<img src="avatar.jpg" />
			<figcaption></figcaption>
		</figure>
	</header>
	<nav>
		<ul>
			<li id="flechita_nav"><a href="#"></a></li>
			{% for cat in categorias %}
			    <li><a href="{% url "categoria" cat.pk %}">{{cat}}</a></li>
			{% endfor %}
			<li id="publicar_nav"><a href="#">Publicar</a></li>
		</ul>
	</nav>

	<section id="contenido">
	    <form method="post">
	    <div id="form">
	        {% csrf_token %}
		    {{form.as_p}}
		    <input type="submit">
		<form>
		</div>
	</section>
	<footer>
		<p><strong>Powered by Platzi!</strong></p>
		<p>Mejorando.la 2013 ®</p>
	</footer>
</body>
</html>

data/templates/hora.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hora</title>
</head>
<body>
    Hola {{user}} la hora es: {{hora|date:"d M Y"}}
</body>
</html>